### ISSUE TITLE
Error in generator

### ISSUE THREAD

**Issue by vorjdux** [naazgull/zapata#35]
The file /usr/share/zapata/gen/Datum.sh is missing in the zgen, when it tries to generate the CouchDB files it generates a blank file because this template file is missing in the zapata built installation. 

I did a workaround creating this file in my local machine and it worked very well generating the .sh files to populate the CouchDB databases.

**Comment by naazgull** [comment]
Hi Matheus.

You are right, forgot to add the file to the debian/install file. Many thanks.
Great work, reading and understanding the code. You really speak "programming" ;)

Cheers,

**Comment by vorjdux** [comment]
Thank you sir ;)
