### ISSUE TITLE
Error to handle a bad HTTP Request

### ISSUE THREAD

**Issue by vorjdux** [naazgull/zapata#51]
After some penetration tests in few requests that is not the default ones to explore the vulnerabilities in some cases after a HTTP Parser error the Zapata lost the connection and can't reply the error message exiting the ZMQ loop breaking the entire service.

There are some log examples:

GET / HTTP/1.1
Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */*
Accept-Charset: iso-8859-1,utf-8;q=0.9,*;q=0.1
Accept-Language: en
Connection: close
Host: ***.***.111.68:443
Pragma: no-cache
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)
X-Forwarded-For: ***.***.123.48
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Resource: /

 | service-layer-node01:79879 ./ZMQClient.cpp:1626
   trace    | 2017-12-19T14:38:57 | > REPLY / 404 | service-layer-node01:79879 ./ZMQClient.cpp:1587
  verbose   | 2017-12-19T14:38:57 |
HTTP/1.1 404 Not Found
Connection: close
Date: Tue, 19 Dec 2017 14:38:57 UTC
Server: zapata RESTful server
Vary: Accept-Language,Accept-Encoding,X-Access-Token,Authorization,E-Tag
X-Error: 1101
X-Status: 404
X-Resource: /

{
        "assertion_failed" : "_container->ok()",
        "code" : 1101,
        "text" : "'\/' could not be found"
}
 | service-layer-node01:79879 ./ZMQClient.cpp:1588
  verbose   | 2017-12-19T14:38:57 | poll event on HTTP/1.1/http://*:-1 | service-layer-node01:79879 ./ZMQPoll.cpp:321
   error    | 2017-12-19T14:38:57 | error while parsing HTTP request: syntax error exception | service-layer-node01:79879 ./ZMQClient.cpp:1621
 emergency  | 2017-12-19T14:38:57 | HTTP socket state doesn't allow you to send a reply without having received a request: '(_performative == zpt::ev::Reply && this->__state == HTTP_REQ) || (_performative != zpt::ev::Reply && this->__state != HTTP_REQ)' failed on file ./ZMQClient.cpp, line 1556 | service-layer-node01:79879 ./ZMQPoll.cpp:420

---

This is in my local env, I added a log line before the assertz to see what are the values tested and it is what I got:

  verbose   | 2017-12-20T14:13:35 | poll event on HTTP/1.1/http://*:-1 | container:9417 ./ZMQPoll.cpp:321
   error    | 2017-12-20T14:14:17 | error while parsing HTTP request: syntax error exception | container:9417 ./ZMQClient.cpp:1639
   info     | 2017-12-20T14:14:17 | >>> zpt::ZMQHttp::send: assertz((7 == 7 && -1 == 1) OR (7 != 7 && -1 != 1)) | container:9417 ./ZMQClient.cpp:1572
 emergency  | 2017-12-20T14:14:17 | HTTP socket state doesn't allow you to send a reply without having received a request: '(_performative == zpt::ev::Reply && this->__state == HTTP_REQ) || (_performative != zpt::ev::Reply && this->__state != HTTP_REQ)' failed on file ./ZMQClient.cpp, line 1574 | container:9417 ./ZMQPoll.cpp:420
   trace    | 2017-12-20T14:14:17 |
/usr/lib/libzapata-zmq.so.0(_ZN3zpt7ZMQHttp4sendENS_4jsonE+0x1435) [0x7f95744ee115]
/usr/lib/libzapata-zmq.so.0(_ZN3zpt7ZMQPoll5replyENS_4jsonENS_10socket_refE+0x1df4) [0x7f95744a5224]
/usr/lib/libzapata-zmq.so.0(_ZN3zpt7ZMQPoll4loopEv+0x950) [0x7f95744a8af0]
/usr/lib/libzapata-rest.so.0(_ZN3zpt10RESTServer5startEv+0xaed) [0x7f9575dbbcad]
/usr/lib/libzapata-rest.so.0(_ZN3zpt13RESTServerPtr6launchEiPPc+0x726) [0x7f9575dc8e36]
zpt() [0x4011f5]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f95751d5830]
zpt() [0x4017e9]
 | container:9417 ./ZMQPoll.cpp:421
terminate called after throwing an instance of 'zmq::error_t'
  what():  Context was terminated
[1]    9417 abort (core dumped)  zpt -c etc/zapata/backend-available/container.conf

To simulate you need just call a telnet to the service http port and call:

```
telnet localhost 8888
> GET /
Ctrl + ]
> quit
Wait few seconds and
telnet localhost 8888
> GET / HTTP/1.1
```

You will be disconnected and the service goes down

---

Thank you!

**Comment by naazgull** [comment]
Closed by commit 989fd5cf75b994d9f850314898dd6737ff4241b2
