### ISSUE TITLE
Focal Fossa (Ubuntu 20.04) compilation breaks in modules that use itself libraries

### ISSUE THREAD

**Issue by vorjdux** [naazgull/zapata#99]
When trying to compile Zapata in Focal Fossa (Ubuntu 20.04) bin_PROGRAMS that use their libraries declared in lib_LTLIBRARIES complain that there is no library available for the executables declared in bin_PROGRAMS (just when the declaration of the library and the executables are declared in the same Makefile.am) so seems to be a problem of dependency in the compilation process between the library and executables (the library needs to be compiled before starting to compile the executables)

**Comment by naazgull** [comment]
Thank you for reporting it, @vorjdux
